version: '3.8'
services:
  prometheus:
    image: prom/prometheus:v2.47.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts/:/etc/prometheus/alerts/
      - ./security/:/etc/prometheus/security/
    ports:
      - "9090:9090"
    restart: unless-stopped