global:
  scrape_interval: 60s
  evaluation_interval: 30s
  external_labels:
    environment: "prod-hardened"

# Security headers and TLS
scrape_configs:
  - job_name: 'hardening_metrics'
    scheme: https
    tls_config:
      cert_file: /etc/prometheus/security/tls/prometheus.crt
      key_file: /etc/prometheus/security/tls/prometheus.key
    basic_auth:
      username: {{ env.PROM_USER }}
      password_file: /etc/prometheus/security/basic_auth.yml
    file_sd_configs:
      - files: ['/etc/prometheus/file_sd/hardened_nodes.yml']

# Alertmanager integration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - '/etc/prometheus/alerts/*.rules'