---
- name: Include all hardening tasks
  include_tasks: ssh.yml
  tags: ssh

- name: Configure firewall
  include_tasks: firewall.yml
  tags: firewall

- name: Set file permissions
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  loop:
    - { path: /etc/passwd, mode: '0644' }
    - { path: /etc/shadow, mode: '0600' }